export const ERROR_CODES = {
  MISSING_INPUT: 'MISSING_INPUT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  TEXT_TOO_SHORT: 'TEXT_TOO_SHORT',
  PARSE_FAILED: 'PARSE_FAILED',
  AI_PARSE_FAILED: 'AI_PARSE_FAILED',
  AI_API_ERROR: 'AI_API_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

export const LIMITS = {
  MAX_FILE_SIZE_MB: 10,
  MIN_TEXT_LENGTH: 100,
  MAX_WEEKS: 52,
  MIN_WEEKS: 1,
  PROJECTS_PER_WEEK: 2,
};
